name = "Anarchronistic"
author = "Sunroses"
version = "1.5.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "613faaa8ff3c02935eba888e65989b268dacb7a11bb4ad8f0485959d1d4d9778"

[versions]
fabric = "0.14.22"
minecraft = "1.19.4"

[options]
acceptable-game-versions = "1.19.3"
