name = "Anarchronistic"
author = "Sunroses"
version = "1.5.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fd107eeb466ee0cfcdcec0bb837e6428e5d38dabe9162d6fae3f3c1a4b6d1a3"

[versions]
fabric = "0.14.22"
minecraft = "1.19.4"

[options]
acceptable-game-versions = "1.19.3"
