name = "Anarchronistic"
author = "Sunroses"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a483c2aa4b62bdcf46f07754a4323358820ae73001a631fe6ad1556845d3a2c3"

[versions]
fabric = "0.14.22"
minecraft = "1.19.4"

[options]
acceptable-game-versions = "1.19.3"
